version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-test-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm i
            - run: export NODE_OPTIONS=--openssl-legacy-provider && npm run affected:deploy --base=<< pipeline.git.base_revision >> --head=HEAD

workflows:
  build-test-and-deploy:
    jobs:
      - build-test-and-deploy